console.log("hi");
var firstname="Aaris";
var secondname="Khan";
console.log(firstname);
console.log(secondname);
var fullname=firstname.concat(secondname);
console.log(fullname);
var length=fullname.length;
console.log(length);
var uppercase=fullname.toUpperCase();
console.log(uppercase);
var lowercase=fullname.toLowerCase();
console.log(lowercase);
var square_root=Math.sqrt(625);
console.log(square_root);
var max=Math.max(56,64);
console.log(max);
var min=Math.min(67,245);
console.log(min);